

access_token_bot_1: "vk1.a.-Y-uRgTgVbpmvPUzOn3f40xKcBW_DgipUL4T6LGa4jbgFOugq_fake"
access_token_bot_2: "vk1.a.-Y-uRgTgVbpmvPUzOn3f40xKcBW_DgipUL4T6LGa4jbgFOugq_fake"

JOINING_A_GROUP_1_TEXT: "Добрый день! Большое спасибо за подписку, {name}. Предлагаем ознакомиться с нашим ассортиментом!"
PLACING_AN_ORDER_1_TEXT: "Большое спасибо за заказ, {name}. Наш менеджер свяжется с Вами в ближайшее время!"

JOINING_A_GROUP_2_TEXT: |
  Привет, {name}! Добро пожаловать в нашу студию трансформации. Предлагаем ознакомиться с нами по ближе.

  Мы - студия трансформации. Твой источник сил, энергии и вдохновения.

  Своё пространство появилось специально, чтобы ты могла расти и личностно развиваться, могла лучше разобраться в себе, понять свое тело, мысли и истинные желания.

  На наших встречах практики проводят психологи, тренеры, коучи и другие специалисты. В наших студиях для тебя:

  + психологические расстановки,

  + ресурсные практики,

  + тренировки,

  + медитации,

  + ретриты,

  + тематические вечера,

  + коуч-сессии,

  + мастер-классы,

  + путешествия.

  Здесь ты научишься верить в себя и любить себя. Договариваться с собой и окружающими. Чувствовать свое состояние и быстро реагировать на его изменения.

  Здесь ты познакомишься с новыми людьми, похожими на тебя и пообщаешься с профессионалами из разных сфер деятельности.

  Мы понимаем, как тебе хочется быть свободной от житейских хлопот, как ты устала искать в себе силы, чтобы двигаться дальше, и как ты нуждаешься в перезагрузке.

  Поэтому у тебя есть Своё пространство. Место, где ты всегда найдешь поддержку, прилив сил и новое видение своего пути.

  *************

  Наш адрес: ул. Красноармейская, 9 (Центр города, рядом с Александровским Пассажем)

  Студия 501, 5 этаж


PLACING_AN_ORDER_2_TEXT: ""

ADMIN_USERS:
  - 180323228

vk_api_version: "5.154"