

access_token: ""

JOINING_A_GROUP_TEXT: "Добрый день! Большое спасибо за подписку, {name}. предлагаем ознакомиться с нашим ассортиментом!"
PLACING_AN_ORDER_TEXT: "Большое спасибо за заказ, {name}. Наш менеджер свяжется с Вами в ближайшее время!"

ADMIN_USERS:
  - 999999999999999999999999999999999999999999999999999

vk_api_version: "5.154"